runtime: python
env: flex
entrypoint: gunicorn -b :$PORT getresource:app
service: getresource

runtime_config:
  python_version: 3

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10

manual_scaling:
  instances: 1

env_variables:
  DB_HOST: "35.200.204.195"
  USER: "root"
  PASSWORD: "root123"
  DATABASE: "RTM"
