steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/front-end:$BUILD_ID','.']
  dir: 'gke-rtm-frontend-cicd/'
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/front-end:$BUILD_ID'] 
  dir: 'gke-rtm-backend-cicd/'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  dir: 'gke-rtm-frontend-cicd/' 
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-example'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - front-end
  - web=gcr.io/$PROJECT_ID/front-end:$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-build-example'
