steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/frontend:$REVISION_ID"]
# Update Deployment
- id: Updating Deployment
  name: gcr.io/cloud-builders/kubectl
    args: ['apply','-f','helloworld.yaml']
    env:
    - CLOUDSDK_COMPUTE_ZONE=asia-south1-c
    - CLOUDSDK_CONTAINER_CLUSTER=clusterx
   # Images
images:
  - gcr.io/$PROJECT_ID/frontend:$REVISION_ID
# Tags
tags:
  - master
  - dev
  - init
