steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world:1.0.$BUILD_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/hello-world:1.0.$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - hello-world
  - web=gcr.io/$PROJECT_ID/hello-world:1.0.$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'
