steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/sdp-demo-app:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/demo-app', 'demo-app=gcr.io/$PROJECT_ID/sdp-demo-app:$SHORT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'
images:
- 'gcr.io/$PROJECT_ID/sdp-demo-app'
