steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/frontend:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['run', 'image', 'helloworld', 'frontend=gcr.io/$PROJECT_ID/frontend:$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo-cluster'
