apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app=my-app
    spec:
      containers:
      - name: hello-app
        image: gcr.io/$PROJECT_ID/hello-app:1.0
        ports:
        - containerPort: 8080
