apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app=gke-rtm-front-end-application
    spec:
      containers:
      - name: gke-rtm-front-end-application
        image: gcr.io/$PROJECT_ID/hello-world:1.0
        ports:
        - containerPort: 8080
