apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-end
  #namespace: logging
  labels:
    app: back-end
  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: web
        image: gcr.io/$PROJECT_ID/back-end:$BUILD_ID
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
