runtime: java
env: flex 
api_version: 1
threadsafe: true
service: backend
handlers:
- url: /.*
  script: this field is required, but ignored
# [START configuration]
endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: ENDPOINTS-SERVICE-NAME
  rollout_strategy: managed
# [END configuration]
