steps:
- name: "gcr.io/cloud-builders/mvn"
  args: ['install']
  dir: 'gke-rtm-backend-cicd/resourcetechnologymapping/'
- name: "gcr.io/cloud-builders/mvn"
  args: ['package']
  dir: 'gke-rtm-backend-cicd/resourcetechnologymapping/'
  artifacts:
   objects:
    location: ['gs://m1048135/']
    paths: ["${_TARGET}"]
- name: gcr.io/cloud-builders/gsutil
  args: ["cp", "gs://m1048135/", "/workspace/kubeconfig"] 
- name: "gcr.io/google_containers/hyperkube:v1.5.3"
  env: ["KUBECONFIG=/workspace/kubeconfig"]
  entrypoint: "/hyperkube"
  args: ["kubectl", "apply", "-f", "/workspace/production"]
  timeout: 180s
