steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'gke-rtm-backend-cicd/resourcetechnologymapping/'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'gke-rtm-backend-cicd/resourcetechnologymapping/'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID','.']
  dir: 'gke-rtm-backend-cicd/resourcetechnologymapping/'
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  dir: 'gke-rtm-backend-cicd/resourcetechnologymapping/'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=apple'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment/
  - back-end
  - web=gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=apple'
