apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: front-end
  name: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: web
        image: gcr.io/gke-mindtree-135/front-end:$BUILDID
        ports:
        - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /
            port: 8090
