steps:
- name: "gcr.io/cloud-builders/mvn"
  args:
  - install
  dir: 'spring-boot-hibernate-crud-demo/'
- name: "gcr.io/cloud-builders/mvn"
  args:
  - package
  dir: 'spring-boot-hibernate-crud-demo/'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID','.']
  dir: 'spring-boot-hibernate-crud-demo/'
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/back-end:1.0.$BUILD_ID']
